version: '3.9'
services:
  bid-buddy-db:
    image: postgres
    restart: always
    container_name: group-finder-db
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_PASSWORD: axample
      PGDATA: /data/postgres
    volumes:
      - 